# Feature Extraction in Text — Full Pipeline

This notebook runs the complete, hand-built pipeline end to end on real
documents scraped from Hacker News (`hackernews_dataset.csv`, produced by
`scrape_hackernews.py`), falling back to the small curated `demo.csv` corpus
if that file isn't present:

1. Load raw text from CSV
2. Preprocess (lowercase, strip punctuation/numbers, tokenize, remove
   stopwords, stem)
3. POS tagging
4. Syntactic features (subject/verb/object, noun/verb counts)
5. Semantic features (rule-based lexical categories)
6. Morphological analysis
7. Lemmatization (vs. stemming)
8. Vocabulary + Bag of Words / Binary BoW
9. One-hot encoding (tokens and POS tags)
10. TF-IDF + document cosine similarity
11. N-grams

All logic comes from `preprocessing.py`, `linguistic_features.py`,
`syntactic_features.py`, `semantic_features.py`, and `features.py` in this
project — no scikit-learn, nltk, or spaCy.

## 1. Setup

In [2]:
import pandas as pd

from preprocessing import (
    preprocess,
    lowercase,
    remove_punctuation_and_numbers,
    tokenize,
    remove_stopwords,
    stem_word,
    stem_tokens,
)
from linguistic_features import (
    pos_tag,
    pos_tag_word,
    morphological_analysis,
    lemmatize_word,
    lemmatize_tokens,
)
from syntactic_features import syntactic_analysis, syntactic_feature_matrix
from semantic_features import semantic_feature_matrix, cosine_similarity_matrix
from features import (
    build_vocabulary,
    bag_of_words,
    binary_bow,
    tf_idf,
    n_grams,
    one_hot_encode_tokens,
    one_hot_encode_categories,
)

pd.set_option("display.width", 120)
pd.set_option("display.max_columns", 30)

## 2. Load raw text from CSV

Reads `hackernews_dataset.csv` (real scraped Hacker News stories, one per
row in a `text` column) if it exists, otherwise falls back to the small
curated `demo.csv` corpus.

In [3]:
from pathlib import Path

csv_path = "hackernews_dataset.csv" if Path("hackernews_dataset.csv").exists() else "demo.csv"
data = pd.read_csv(csv_path)
corpus = data["text"].tolist()

print(f"Loaded {len(corpus)} documents from {csv_path}\n")
for i, doc in enumerate(corpus):
    print(f"Doc {i}: {doc}")

Loaded 50 documents from hackernews_dataset.csv

Doc 0: The Therapeutic Potential of Apigenin (2018)
Doc 1: Interactive Physics
Doc 2: The Economics of the Intelligence Frontier
Doc 3: Packslip – signed release manifest for archives, installers, or executables
Doc 4: The Innovative HP Computer Behind a Hedge Fund Pioneer
Doc 5: Federal judge again rules against Musk's xAI
Doc 6: TIL: Using Blender with coding agents on macOS
Doc 7: Show HN: MarkFlowy – A open source Markdown editor rebuilt for large documents. I maintain MarkFlowy, a desktop Markdown editor for Windows, macOS, and Linux. I’ve spent the past two months rebuilding its editor core, mainly to improve performance with larger documents. The changes are part of v0.100.0. In testing, a 2 MB Markdown document opened in about a second. I’d be interested to see how it performs with other people’s documents and hardware. Opening speed was one part of the work. I also worked on editing long documents and copying and cutting large selections. Much of the overhead came from repeatedly processing the entire document or doing unnecessary work within a single operation. Finding and reducing that work took up a substantial part of the rewrite. I want to thank the users who reported bugs, slow operations, and awkward interactions. Those reports helped me understand where to focus. The rewrite changes some editing behavior, and there are still rough edges to work through. If you regularly work with long Markdown documents, I’d appreciate feedback on anything that still feels slow or gets in your way. Project and downloads: https://github.com/drl990114/MarkFlowy
Doc 8: How would LLMs vote in upcoming German state elections?
Doc 9: Show HN: Object Remover – AI Video Object Remover Online
Doc 10: You Could Have Come Up with Speculative Decoding
Doc 11: Gompertz–Makeham Law of Mortality
Doc 12: Lost Bytes at the Crossroads Between User and Kernel-Level Memory Management [pdf]
Doc 13: A 30-Year-Old Japanese Book Predicted Our Productivity Crisis
Doc 14: Infinite Slop
Doc 15: Ask HN: How to Reactivate ChatGPT Account?. I received a notice that my account was deactivated, but I wasn't doing anything weird or inappropriate. I don't have access to my chats anymore but was able to see some of my recent chats and could annotate them here, there's nothing weird about it: https://imgur.com/a/Q9hEo0e Is there any way I could escalate it to someone at OpenAI to reinstate my account? I filed an appeal but I don't know if that's enough.
Doc 16: Mortgage Calculator
Doc 17: LLMs Are the New Wikipedia
Doc 18: The Claude Compiler Is Dead. Long Live the Claude Compiler
Doc 19: Older People Surpass the Young in the World for the First Time in History
Doc 20: Modern-Day American Imperialism: Middle East and Beyond (2010) [video]
Doc 21: Icy Moons Are Ocean Worlds
Doc 22: The Currency Killer Part II: Howard Lutnick
Doc 23: Trees use a 'muscle' to correct posture–a newly discovered role for tension wood
Doc 24: Support Local Variables
Doc 25: Tim Berners-Lee: A Call for Continued Open Standards and Neutrality (2010)
Doc 26: QBittorrent breaks out of sandbox to commit crimes
Doc 27: Reddits anti self promo policies are destroying startups. I’m posting this here because Reddit just bans me whenever I talk about it. So let me explain. Reddit has these anti self promo policies to prevent spam. BUT they are enforced so strictly by Reddit, the mods and even the users that it becomes near impossible to share a startup. Now, Reddit in of itself wouldn’t get your startup big, but it prevents you from even being rejected. This causes people who make bad startups to not even know their thing is bad, leading to long drawn out failures. This even affects things outside of Reddit by shrinking the available spaces you can share your startup. So much for Redditors being for the common man .
Doc 28: Show HN: Dsnitch – Real-time, zero-config Docker egress inspector via eBPF. Hi HN, I built dsnitch because I wanted a zero-config, bandwhich-style live TUI to see what my homelab Docker containers are connecting to—without running sidecar proxies, modifying container configs, or relying on reverse DNS (fails on anycast CDN IPs). Just run the binary and it automatically discovers running containers. Under the hood, it's written in Rust and attaches eBPF probes to the unified cgroup v2 hierarchy and TCP state tracepoints. To map IPs back to domain names accurately, it passively snoops raw UDP/53 DNS responses per cgroup and decodes them in userspace using Hickory DNS. The terminal interface is built with Ratatui. It targets Linux 5.8+ and does not modify or filter network packets in any way. It's strictly read-only. Happy to answer questions or hear your feedback!
Doc 29: Bad Vibes Coding
Doc 30: I'm teaching an introductory 12 week course on Quantum Oracle Engineering
Doc 31: Show HN: Claude-hl – syntax colours for shell commands in Claude Code output
Doc 32: Schemy Lisp En DOS
Doc 33: Generate game ready sound effects from text
Doc 34: Ask HN: Are we normalizing surveillance in the name of safety?. I don’t know if this is just my imagination. In recent years, I feel like the whole world is slowly moving toward this direction: “Because we need to protect people, we need to monitor them.” As a Taiwanese person, I’m very familiar with this kind of logic from the CCP next door. But for some reason, I feel like more and more of the world is also moving in this direction. For example: * Asking an important open-source infrastructure project like Linux to add age verification. * Credit card companies asking Japan to follow all kinds of unreasonable rules. * Using courts to force companies, in the name of human rights or safety, to monitor cloud data. * Requiring VPNs to be controlled or regulated. These are just some simple examples. I don’t have detailed statistics, but I really feel like there have been more and more cases like this recently. It is often wrapped in something morally justified, and then surveillance and control are introduced underneath it. The CCP next door has always used this kind of logic. Officially, everything is for protection and safety. Encryption is heavily restricted. Whenever these policies are introduced, there are also many people defending them. Many people do not really feel that their own rights are being violated. Until one day, the restrictions keep expanding and become something like a censorship system where almost anything can be punished. On mainland Chinese platforms, if you try to have a deeper discussion about certain topics, or even just ask for opinions, it is very easy to get banned. Right now, fortunately, there are still many people around the world who keep pushing back against different kinds of surveillance that are packaged as “morally necessary.” But what I’m afraid of is this: What if people slowly become used to it? What if everyone becomes more and more insensitive to these things, like many people in mainland China, and only realizes what happened when almost nothing can be said anymore? At that point, it may already be too late. As a side note, the security and identity system in mainland China is basically built more from the perspective of the state. So you can see many things like: * A phone number is required almost everywhere. * Email is not used very much. * Communication is mainly through QQ or WeChat. * Passkeys are not common. Most identity verification is based on phone numbers. * Many services look anonymous, but are actually tied to your real identity. A lot of the “security” mechanisms are related to the state, including speech and political control, rather than the personal security or privacy of the user. Apps also like to put advertisements everywhere. One app tries to do everything. Many apps constantly encourage people to borrow money. Even on phones and other hardware, anything that allows you to type text may potentially contain blocked words. Some topics basically cannot be discussed. Xi Jinping is one obvious example. Even related words or associations, such as “Xi” or Winnie the Pooh, can become sensitive. China is also very strong in AI, partly because there is so much data and not much privacy. Sometimes you can see Chinese AI systems that speak in a way that feels very similar to how real people think and talk. My guess is that this is partly because a lot of real human-to-human conversations have been used for training, including private conversations. There is probably much more I could add. But the main point is not really China. What I am worried about is that one day, even installing Linux on my own computer may require real-name verification. That kind of thing sounds terrifying to me. Maybe I’m overthinking it, but I really feel like the direction is becoming more obvious. I’m curious what people here think. Do you feel the same way? Do you think this is actually becoming a broader trend?
Doc 35: Scientists map key protein interactions linked with profound autism
Doc 36: The 92-Year-Old Mathematician and the Teenage Apprentice
Doc 37: AI coding agents forget the codebase between sessions
Doc 38: FOSS vs. Arthritis
Doc 39: Floating Point – The Origin Story
Doc 40: AI Slop
Doc 41: 2026 Hugo Awards
Doc 42: What different world maps get right and what they get wrong
Doc 43: Who said a tech addict can't be comfortable far from home?
Doc 44: Did you say AI-mish?
Doc 45: Devnote – Gittykat
Doc 46: Scientists Hunting Dark Matter Found Something Strange
Doc 47: Yes, We're Entering the Era of Artificial General Intelligence
Doc 48: Show HN: My portfolio website as a Windows 98 style web OS
Doc 49: SSH on the Go

## 3. Preprocessing

`preprocess()` runs lowercase -> strip punctuation/numbers -> tokenize ->
remove stopwords -> stem, in one call. We also keep a lighter "raw tokens"
version per document (lowercased and tokenized, but *not* stopword-stripped
or stemmed) for the linguistic analysis steps below, since POS tagging and
morphology need function words and full word forms to work with.

In [4]:
processed_docs = [preprocess(doc) for doc in corpus]
raw_tokens_per_doc = [
    tokenize(remove_punctuation_and_numbers(lowercase(doc))) for doc in corpus
]

print("=== Tokens after full preprocessing (stopwords removed, stemmed) ===")
for i, tokens in enumerate(processed_docs):
    print(f"Doc {i}: {tokens}")

=== Tokens after full preprocessing (stopwords removed, stemmed) ===
Doc 0: ['therapeutic', 'potential', 'apigenin']
Doc 1: ['interactive', 'physic']
Doc 2: ['economic', 'intelligence', 'frontier']
Doc 3: ['packslip', 'sign', 'release', 'manifest', 'archiv', 'installer', 'executabl']
Doc 4: ['innovative', 'hp', 'computer', 'behind', 'hedge', 'fund', 'pioneer']
Doc 5: ['federal', 'judge', 'rul', 'musk', 's', 'xai']
Doc 6: ['til', 'using', 'blender', 'cod', 'agent', 'maco']
Doc 7: ['show', 'hn', 'markflowy', 'open', 'source', 'markdown', 'editor', 'rebuilt', 'large', 'document', 'maintain', 'markflowy', 'desktop', 'markdown', 'editor', 'window', 'maco', 'linux', 've', 'spent', 'past', 'two', 'month', 'rebuild', 'editor', 'core', 'main', 'improve', 'performance', 'larger', 'document', 'chang', 'part', 'v', 'test', 'mb', 'markdown', 'document', 'open', 'second', 'd', 'interest', 'see', 'how', 'perform', 'other', 'people', 's', 'document', 'hardware', 'open', 'spe', 'one', 'part', 'work', 'also', 'work', 'edit', 'long', 'document', 'copy', 'cutt', 'large', 'selection', 'much', 'overhead', 'came', 'repeated', 'process', 'entire', 'document', 'unnecessary', 'work', 'within', 'single', 'operation', 'find', 'reduc', 'work', 'took', 'substantial', 'part', 'rewrite', 'want', 'thank', 'user', 'who', 'report', 'bug', 'slow', 'operation', 'awkward', 'interaction', 'report', 'help', 'understand', 'where', 'focu', 'rewrite', 'chang', 'some', 'edit', 'behavior', 'there', 'still', 'rough', 'edg', 'work', 'regular', 'work', 'long', 'markdown', 'document', 'd', 'appreciate', 'feedback', 'anyth', 'still', 'feel', 'slow', 'get', 'way', 'project', 'download', 'http', 'github', 'com', 'drl', 'markflowy']
Doc 8: ['how', 'would', 'llm', 'vote', 'upcom', 'german', 'state', 'election']
Doc 9: ['show', 'hn', 'object', 'remover', 'ai', 'video', 'object', 'remover', 'online']
Doc 10: ['could', 'come', 'speculative', 'decod']
Doc 11: ['gompertz', 'makeham', 'law', 'mortality']
Doc 12: ['lost', 'byt', 'crossroad', 'user', 'kernel', 'level', 'memory', 'management', 'pdf']
Doc 13: ['year', 'old', 'japanese', 'book', 'predict', 'productivity', 'crisi']
Doc 14: ['infinite', 'slop']
Doc 15: ['ask', 'hn', 'how', 'reactivate', 'chatgpt', 'account', 'receiv', 'notice', 'account', 'deactivat', 'wasn', 't', 'anyth', 'weird', 'inappropriate', 'don', 't', 'acces', 'chat', 'anymore', 'able', 'see', 'some', 'recent', 'chat', 'could', 'annotate', 'here', 'there', 's', 'noth', 'weird', 'http', 'imgur', 'com', 'q', 'heo', 'e', 'there', 'any', 'way', 'could', 'escalate', 'someone', 'openai', 'reinstate', 'account', 'fil', 'appeal', 'don', 't', 'know', 's', 'enough']
Doc 16: ['mortgage', 'calculator']
Doc 17: ['llm', 'new', 'wikipedia']
Doc 18: ['claude', 'compiler', 'dead', 'long', 'live', 'claude', 'compiler']
Doc 19: ['older', 'people', 'surpas', 'young', 'world', 'first', 'time', 'history']
Doc 20: ['modern', 'day', 'american', 'imperialism', 'middle', 'east', 'beyond', 'video']
Doc 21: ['icy', 'moon', 'ocean', 'world']
Doc 22: ['currency', 'killer', 'part', 'ii', 'howard', 'lutnick']
Doc 23: ['tre', 'use', 'muscle', 'correct', 'posture', 'new', 'discover', 'role', 'tension', 'wood']
Doc 24: ['support', 'local', 'variabl']
Doc 25: ['tim', 'berner', 'lee', 'call', 'continu', 'open', 'standard', 'neutrality']
Doc 26: ['qbittorrent', 'break', 'sandbox', 'commit', 'crim']
Doc 27: ['reddit', 'anti', 'self', 'promo', 'polici', 'destroy', 'startup', 'm', 'post', 'here', 'because', 'reddit', 'just', 'ban', 'whenever', 'talk', 'let', 'explain', 'reddit', 'anti', 'self', 'promo', 'polici', 'prevent', 'spam', 'enforc', 'strict', 'reddit', 'mod', 'even', 'user', 'becom', 'near', 'impossible', 'share', 'startup', 'now', 'reddit', 'itself', 'wouldn', 't', 'get', 'startup', 'big', 'prevent', 'even', 'reject', 'caus', 'people', 'who', 'make', 'bad', 'startup', 'even', 'know', 'thing', 'bad', 'lead', 'long', 'drawn', 'failur', 'even', 'affect', 'thing', 'outside', 'reddit', 'shrink', 'available', 'spac', 'can', 'share', 'startup', 'much', 'redditor', 'common', 'man']
Doc 28: ['show', 'hn', 'dsnitch', 'real', 'time', 'zero', 'config', 'docker', 'egres', 'inspector', 'via', 'ebpf', 'hi', 'hn', 'built', 'dsnitch', 'because', 'want', 'zero', 'config', 'bandwhich', 'style', 'live', 'tui', 'see', 'what', 'homelab', 'docker', 'container', 'connect', 'without', 'runn', 'sidecar', 'proxi', 'modify', 'container', 'config', 'rely', 'reverse', 'dns', 'fail', 'anycast', 'cdn', 'ips', 'just', 'run', 'binary', 'automatical', 'discover', 'runn', 'container', 'hood', 's', 'written', 'rust', 'attach', 'ebpf', 'prob', 'unifi', 'cgroup', 'v', 'hierarchy', 'tcp', 'state', 'tracepoint', 'map', 'ips', 'back', 'domain', 'nam', 'accurate', 'passive', 'snoop', 'raw', 'udp', 'dns', 'respons', 'per', 'cgroup', 'decod', 'userspace', 'using', 'hickory', 'dns', 'terminal', 'interface', 'built', 'ratatui', 'target', 'linux', 'modify', 'filter', 'network', 'packet', 'any', 'way', 's', 'strict', 'read', 'only', 'happy', 'answer', 'question', 'hear', 'feedback']
Doc 29: ['bad', 'vib', 'cod']
Doc 30: ['m', 'teach', 'introductory', 'week', 'course', 'quantum', 'oracle', 'engineer']
Doc 31: ['show', 'hn', 'claude', 'hl', 'syntax', 'colour', 'shell', 'command', 'claude', 'code', 'output']
Doc 32: ['schemy', 'lisp', 'en', 'dos']
Doc 33: ['generate', 'game', 'ready', 'sound', 'effect', 'text']
Doc 34: ['ask', 'hn', 'normaliz', 'surveillance', 'name', 'safety', 'don', 't', 'know', 'just', 'imagination', 'recent', 'year', 'feel', 'like', 'whole', 'world', 'slow', 'mov', 'toward', 'direction', 'because', 'need', 'protect', 'people', 'need', 'monitor', 'taiwanese', 'person', 'm', 'very', 'familiar', 'kind', 'logic', 'ccp', 'next', 'door', 'some', 'reason', 'feel', 'like', 'more', 'more', 'world', 'also', 'mov', 'direction', 'example', 'ask', 'important', 'open', 'source', 'infrastructure', 'project', 'like', 'linux', 'add', 'age', 'verification', 'credit', 'card', 'compani', 'ask', 'japan', 'follow', 'all', 'kind', 'unreasonable', 'rul', 'using', 'court', 'force', 'compani', 'name', 'human', 'right', 'safety', 'monitor', 'cloud', 'data', 'requir', 'vpn', 'controll', 'regulat', 'just', 'some', 'simple', 'exampl', 'don', 't', 'detail', 'statistic', 'real', 'feel', 'like', 'there', 'more', 'more', 'cas', 'like', 'recent', 'often', 'wrapp', 'someth', 'moral', 'justifi', 'surveillance', 'control', 'introduc', 'underneath', 'ccp', 'next', 'door', 'alway', 'used', 'kind', 'logic', 'official', 'everyth', 'protection', 'safety', 'encryption', 'heavi', 'restrict', 'whenever', 'polici', 'introduc', 'there', 'also', 'many', 'people', 'defend', 'many', 'people', 'real', 'feel', 'own', 'right', 'violat', 'until', 'one', 'day', 'restriction', 'keep', 'expand', 'become', 'someth', 'like', 'censorship', 'system', 'where', 'almost', 'anyth', 'can', 'punish', 'mainland', 'chinese', 'platform', 'try', 'deeper', 'discussion', 'certain', 'topic', 'even', 'just', 'ask', 'opinion', 'very', 'easy', 'get', 'bann', 'right', 'now', 'fortunate', 'there', 'still', 'many', 'people', 'around', 'world', 'who', 'keep', 'push', 'back', 'different', 'kind', 'surveillance', 'packag', 'moral', 'necessary', 'what', 'm', 'afraid', 'what', 'people', 'slow', 'become', 'used', 'what', 'everyone', 'becom', 'more', 'more', 'insensitive', 'thing', 'like', 'many', 'people', 'mainland', 'china', 'only', 'realiz', 'what', 'happen', 'when', 'almost', 'noth', 'can', 'said', 'anymore', 'point', 'may', 'already', 'too', 'late', 'side', 'note', 'security', 'identity', 'system', 'mainland', 'china', 'basical', 'built', 'more', 'perspective', 'state', 'can', 'see', 'many', 'thing', 'like', 'phone', 'number', 'requir', 'almost', 'everywhere', 'email', 'used', 'very', 'much', 'communication', 'main', 'qq', 'wechat', 'passkey', 'common', 'most', 'identity', 'verification', 'bas', 'phone', 'number', 'many', 'servic', 'look', 'anonymou', 'actual', 'tied', 'real', 'identity', 'lot', 'security', 'mechanism', 'relat', 'state', 'includ', 'speech', 'political', 'control', 'rather', 'personal', 'security', 'privacy', 'user', 'app', 'also', 'like', 'put', 'advertisement', 'everywhere', 'one', 'app', 'tri', 'everyth', 'many', 'app', 'constant', 'encourage', 'people', 'borrow', 'money', 'even', 'phon', 'other', 'hardware', 'anyth', 'allow', 'type', 'text', 'may', 'potential', 'contain', 'block', 'word', 'some', 'topic', 'basical', 'cannot', 'discuss', 'xi', 'jinp', 'one', 'obviou', 'example', 'even', 'relat', 'word', 'association', 'such', 'xi', 'winnie', 'pooh', 'can', 'become', 'sensitive', 'china', 'also', 'very', 'strong', 'ai', 'part', 'because', 'there', 'much', 'data', 'much', 'privacy', 'sometim', 'can', 'see', 'chinese', 'ai', 'system', 'speak', 'way', 'feel', 'very', 'similar', 'how', 'real', 'people', 'think', 'talk', 'gues', 'part', 'because', 'lot', 'real', 'human', 'human', 'conversation', 'used', 'train', 'includ', 'private', 'conversation', 'there', 'probab', 'much', 'more', 'could', 'add', 'main', 'point', 'real', 'china', 'what', 'worri', 'one', 'day', 'even', 'install', 'linux', 'own', 'computer', 'may', 'require', 'real', 'name', 'verification', 'kind', 'thing', 'sound', 'terrify', 'maybe', 'm', 'overthink', 'real', 'feel', 'like', 'direction', 'becom', 'more', 'obviou', 'm', 'curiou', 'what', 'people', 'here', 'think', 'feel', 'same', 'way', 'think', 'actual', 'becom', 'broader', 'trend']
Doc 35: ['scientist', 'map', 'key', 'protein', 'interaction', 'link', 'profound', 'autism']
Doc 36: ['year', 'old', 'mathematician', 'teenage', 'apprentice']
Doc 37: ['ai', 'cod', 'agent', 'forget', 'codebase', 'session']
Doc 38: ['fos', 'vs', 'arthriti']
Doc 39: ['float', 'point', 'origin', 'story']
Doc 40: ['ai', 'slop']
Doc 41: ['hugo', 'award']
Doc 42: ['what', 'different', 'world', 'map', 'get', 'right', 'what', 'get', 'wrong']
Doc 43: ['who', 'said', 'tech', 'addict', 'can', 't', 'comfortable', 'far', 'home']
Doc 44: ['say', 'ai', 'mish']
Doc 45: ['devnote', 'gittykat']
Doc 46: ['scientist', 'hunt', 'dark', 'matter', 'found', 'someth', 'strange']
Doc 47: ['yes', 're', 'enter', 'era', 'artificial', 'general', 'intelligence']
Doc 48: ['show', 'hn', 'portfolio', 'website', 'window', 'style', 'web', 'os']
Doc 49: ['ssh', 'go']

## 4. POS Tagging

Rule-based tagging (closed-class lexicon + suffix rules) on the raw tokens
of every document, shown as one combined table.

In [5]:
pos_rows = []
for doc_index, tokens in enumerate(raw_tokens_per_doc):
    for word, tag in pos_tag(tokens):
        pos_rows.append({"doc": doc_index, "word": word, "pos_tag": tag})

pos_df = pd.DataFrame(pos_rows)
pos_df

      doc         word pos_tag
0       0          the     DET
1       0  therapeutic     ADJ
2       0    potential     ADJ
3       0           of    PREP
4       0     apigenin    NOUN
...   ...          ...     ...
1548   48           os    NOUN
1549   49          ssh    NOUN
1550   49           on    PREP
1551   49          the     DET
1552   49           go    NOUN

[1553 rows x 3 columns]

## 5. Syntactic Features

Heuristic subject/verb/object extraction (first nominal before/after the
first verb) plus noun/verb counts, one row per document.

In [6]:
syntactic_frames = []
for doc_index, tokens in enumerate(raw_tokens_per_doc):
    tagged = pos_tag(tokens)
    doc_syntax = syntactic_analysis(tagged)
    doc_syntax.insert(0, "doc", doc_index)
    syntactic_frames.append(doc_syntax)

syntactic_df = pd.concat(syntactic_frames, ignore_index=True)
syntactic_df

    doc     subject        verb        object  token_count  noun_count  verb_count  has_subject_verb_object
0     0        None        None          None            5           1           0                    False
1     1        None        None          None            2           1           0                    False
2     2        None        None          None            6           3           0                    False
3     3    packslip      signed       release            9           6           1                     True
4     4        None        None          None            9           6           0                    False
5     5        None        None          None            8           6           0                    False
6     6         til       using       blender            8           4           2                     True
7     7        show  rebuilding           its          196         105          25                     True
8     8         how    upcoming        german            9           7           1                     True
9     9        None        None          None            9           9           0                    False
10   10         you        have          come            8           2           2                     True
11   11        None        None          None            5           4           0                    False
12   12        None        None          None           13           9           0                    False
13   13        year   predicted           our            9           6           1                     True
14   14        None        None          None            2           2           0                    False
15   15         ask    received        notice           91          47          10                     True
16   16        None        None          None            2           2           0                    False
17   17        llms         are           new            5           3           1                     True
18   18      claude          is          dead           10           6           1                     True
19   19        None        None          None           14           7           0                    False
20   20        None        None          None            9           8           0                    False
21   21         icy         are         ocean            5           4           1                     True
22   22        None        None          None            7           6           0                    False
23   23       trees  discovered          role           14           8           1                     True
24   24        None        None          None            3           2           0                    False
25   25         tim   continued          open           11           7           1                     True
26   26        None        None          None            8           5           0                    False
27   27     reddits         are      startups          126          67          13                     True
28   28        show      wanted          zero          145          90          11                     True
29   29         bad      coding          None            3           2           1                    False
30   30           i    teaching  introductory           11           6           2                     True
31   31        None        None          None           13          11           0                    False
32   32        None        None          None            4           4           0                    False
33   33        None        None          None            7           6           0                    False
34   34         ask         are            we          668         346         101                     True
35   35  scientists      linked      profound            9           7           1                     True
36   36        None        None          None            8           5           0                    False
37   37          ai      coding        agents            8           5           1                     True
38   38        None        None          None            3           3           0                    False
39   39        None    floating         point            5           3           1                    False
40   40        None        None          None            2           2           0                    False
41   41        None        None          None            2           2           0                    False
42   42        None        None          None           11           9           0                    False
43   43         who        said          tech           12           7           2                     True
44   44        None         did           you            5           3           1                    False
45   45        None        None          None            2           2           0                    False
46   46  scientists     hunting          dark            7           4           3                     True
47   47         yes    entering           era           10           4           1                     True
48   48        None        None          None           11           8           0                    False
49   49        None        None          None            4           2           0                    False

## 6. Semantic Features

Counts of tokens per hand-written lexical category (action, animal, place,
object, positive_description, descriptive) from `SEMANTIC_LEXICON`.

In [7]:
semantic_df = semantic_feature_matrix(raw_tokens_per_doc)
semantic_df

    action  animal  place  object  positive_description  descriptive
0        0       0      0       0                     0            0
1        0       0      0       0                     0            0
2        0       0      0       0                     0            0
3        0       0      0       0                     0            0
4        0       0      0       0                     0            0
5        0       0      0       0                     0            0
6        0       0      0       0                     0            0
7        0       0      0       0                     0            0
8        0       0      0       0                     0            0
9        0       0      0       0                     0            0
10       0       0      0       0                     0            0
11       0       0      0       0                     0            0
12       0       0      0       0                     0            0
13       0       0      0       1                     0            0
14       0       0      0       0                     0            0
15       0       0      0       0                     0            0
16       0       0      0       0                     0            0
17       0       0      0       0                     0            0
18       0       0      0       0                     0            0
19       0       0      1       0                     0            1
20       0       0      0       0                     0            0
21       0       0      0       0                     0            0
22       0       0      0       0                     0            0
23       0       0      0       0                     0            0
24       0       0      0       0                     0            0
25       0       0      0       0                     0            0
26       0       0      0       0                     0            0
27       0       0      0       0                     0            0
28       4       0      0       0                     1            0
29       0       0      0       0                     0            0
30       0       0      0       0                     0            0
31       0       0      0       0                     0            0
32       0       0      0       0                     0            0
33       0       0      0       0                     0            0
34       1       0      3       0                     0            1
35       0       0      0       0                     0            0
36       0       0      0       0                     0            0
37       0       0      0       0                     0            0
38       0       0      0       0                     0            0
39       0       0      0       0                     0            0
40       0       0      0       0                     0            0
41       0       0      0       0                     0            0
42       0       0      1       0                     0            0
43       0       0      0       0                     0            0
44       0       0      0       0                     0            0
45       0       0      0       0                     0            0
46       0       0      0       0                     0            0
47       0       0      0       0                     0            0
48       0       0      0       0                     0            0
49       0       0      0       0                     0            0

## 7. Morphological Analysis

Per-word shape and inflection features (length, vowel/consonant counts,
prefix/suffix, plural/gerund/past-tense/comparative/superlative flags) for
every document, combined into one table.

In [8]:
morph_frames = []
for doc_index, tokens in enumerate(raw_tokens_per_doc):
    doc_morph = morphological_analysis(tokens)
    doc_morph.insert(0, "doc", doc_index)
    morph_frames.append(doc_morph)

morph_df = pd.concat(morph_frames, ignore_index=True)
morph_df

,doc,word,length,num_vowels,num_consonants,prefix3,suffix3,is_capitalized,is_plural,is_gerund,is_past_tense,is_comparative,is_superlative
0,0,the,3,1,2,the,the,False,False,False,False,False,False
1,0,therapeutic,11,5,6,the,tic,False,False,False,False,False,False
2,0,potential,9,4,5,pot,ial,False,False,False,False,False,False
3,0,of,2,1,1,of,of,False,False,False,False,False,False
4,0,apigenin,8,4,4,api,nin,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,48,os,2,1,1,os,os,False,False,False,False,False,False
1549,49,ssh,3,0,3,ssh,ssh,False,False,False,False,False,False
1550,49,on,2,1,1,on,on,False,False,False,False,False,False
1551,49,the,3,1,2,the,the,False,False,False,False,False,False
1552,49,go,2,1,1,go,go,False,False,False,False,False,False

## 8. Lemmatization vs. Stemming

Both reduce a word to a base form, but the stemmer just chops suffixes
(sometimes producing fragments that aren't real words), while the
lemmatizer aims to return an actual dictionary word. Comparison shown on
stopword-free tokens from every document.

In [9]:
lemma_rows = []
for doc_index, tokens in enumerate(raw_tokens_per_doc):
    filtered = remove_stopwords(tokens)
    for word in filtered:
        lemma_rows.append({
            "doc": doc_index,
            "word": word,
            "stem": stem_word(word),
            "lemma": lemmatize_word(word),
        })

lemma_df = pd.DataFrame(lemma_rows)
lemma_df

      doc         word         stem        lemma
0       0  therapeutic  therapeutic  therapeutic
1       0    potential    potential    potential
2       0     apigenin     apigenin     apigenin
3       1  interactive  interactive  interactive
4       1      physics       physic       physic
...   ...          ...          ...          ...
1038   48        style        style        style
1039   48          web          web          web
1040   48           os           os           os
1041   49          ssh          ssh          ssh
1042   49           go           go           go

[1043 rows x 4 columns]

## 9. Vocabulary

Built from the fully preprocessed (stopword-free, stemmed) tokens.

In [10]:
vocab = build_vocabulary(processed_docs)
print(f"Vocabulary size: {len(vocab)}")
vocab

Vocabulary size: 626

['able',
 'acces',
 'account',
 'accurate',
 'actual',
 'add',
 'addict',
 'advertisement',
 'affect',
 'afraid',
 'age',
 'agent',
 'ai',
 'all',
 'allow',
 'almost',
 'already',
 'also',
 'alway',
 'american',
 'annotate',
 'anonymou',
 'answer',
 'anti',
 'any',
 'anycast',
 'anymore',
 'anyth',
 'apigenin',
 'app',
 'appeal',
 'appreciate',
 'apprentice',
 'archiv',
 'around',
 'arthriti',
 'artificial',
 'ask',
 'association',
 'attach',
 'autism',
 'automatical',
 'available',
 'award',
 'awkward',
 'back',
 'bad',
 'ban',
 'bandwhich',
 'bann',
 'bas',
 'basical',
 'because',
 'becom',
 'become',
 'behavior',
 'behind',
 'berner',
 'beyond',
 'big',
 'binary',
 'blender',
 'block',
 'book',
 'borrow',
 'break',
 'broader',
 'bug',
 'built',
 'byt',
 'calculator',
 'call',
 'came',
 'can',
 'cannot',
 'card',
 'cas',
 'caus',
 'ccp',
 'cdn',
 'censorship',
 'certain',
 'cgroup',
 'chang',
 'chat',
 'chatgpt',
 'china',
 'chinese',
 'claude',
 'cloud',
 'cod',
 'code',
 'codebase',
 'colour',
 'com',
 'come',
 'comfortable',
 'command',
 'commit',
 'common',
 'communication',
 'compani',
 'compiler',
 'computer',
 'config',
 'connect',
 'constant',
 'contain',
 'container',
 'continu',
 'control',
 'controll',
 'conversation',
 'copy',
 'core',
 'correct',
 'could',
 'course',
 'court',
 'credit',
 'crim',
 'crisi',
 'crossroad',
 'curiou',
 'currency',
 'cutt',
 'd',
 'dark',
 'data',
 'day',
 'deactivat',
 'dead',
 'decod',
 'deeper',
 'defend',
 'desktop',
 'destroy',
 'detail',
 'devnote',
 'different',
 'direction',
 'discover',
 'discuss',
 'discussion',
 'dns',
 'docker',
 'document',
 'domain',
 'don',
 'door',
 'dos',
 'download',
 'drawn',
 'drl',
 'dsnitch',
 'e',
 'east',
 'easy',
 'ebpf',
 'economic',
 'edg',
 'edit',
 'editor',
 'effect',
 'egres',
 'election',
 'email',
 'en',
 'encourage',
 'encryption',
 'enforc',
 'engineer',
 'enough',
 'enter',
 'entire',
 'era',
 'escalate',
 'even',
 'everyone',
 'everyth',
 'everywhere',
 'exampl',
 'example',
 'executabl',
 'expand',
 'explain',
 'fail',
 'failur',
 'familiar',
 'far',
 'federal',
 'feedback',
 'feel',
 'fil',
 'filter',
 'find',
 'first',
 'float',
 'focu',
 'follow',
 'force',
 'forget',
 'fortunate',
 'fos',
 'found',
 'frontier',
 'fund',
 'game',
 'general',
 'generate',
 'german',
 'get',
 'github',
 'gittykat',
 'go',
 'gompertz',
 'gues',
 'happen',
 'happy',
 'hardware',
 'hear',
 'heavi',
 'hedge',
 'help',
 'heo',
 'here',
 'hi',
 'hickory',
 'hierarchy',
 'history',
 'hl',
 'hn',
 'home',
 'homelab',
 'hood',
 'how',
 'howard',
 'hp',
 'http',
 'hugo',
 'human',
 'hunt',
 'icy',
 'identity',
 'ii',
 'imagination',
 'imgur',
 'imperialism',
 'important',
 'impossible',
 'improve',
 'inappropriate',
 'includ',
 'infinite',
 'infrastructure',
 'innovative',
 'insensitive',
 'inspector',
 'install',
 'installer',
 'intelligence',
 'interaction',
 'interactive',
 'interest',
 'interface',
 'introduc',
 'introductory',
 'ips',
 'itself',
 'japan',
 'japanese',
 'jinp',
 'judge',
 'just',
 'justifi',
 'keep',
 'kernel',
 'key',
 'killer',
 'kind',
 'know',
 'large',
 'larger',
 'late',
 'law',
 'lead',
 'lee',
 'let',
 'level',
 'like',
 'link',
 'linux',
 'lisp',
 'live',
 'llm',
 'local',
 'logic',
 'long',
 'look',
 'lost',
 'lot',
 'lutnick',
 'm',
 'maco',
 'main',
 'mainland',
 'maintain',
 'make',
 'makeham',
 'man',
 'management',
 'manifest',
 'many',
 'map',
 'markdown',
 'markflowy',
 'mathematician',
 'matter',
 'may',
 'maybe',
 'mb',
 'mechanism',
 'memory',
 'middle',
 'mish',
 'mod',
 'modern',
 'modify',
 'money',
 'monitor',
 'month',
 'moon',
 'moral',
 'more',
 'mortality',
 'mortgage',
 'most',
 'mov',
 'much',
 'muscle',
 'musk',
 'nam',
 'name',
 'near',
 'necessary',
 'need',
 'network',
 'neutrality',
 'new',
 'next',
 'normaliz',
 'note',
 'noth',
 'notice',
 'now',
 'number',
 'object',
 'obviou',
 'ocean',
 'official',
 'often',
 'old',
 'older',
 'one',
 'online',
 'only',
 'open',
 'openai',
 'operation',
 'opinion',
 'oracle',
 'origin',
 'os',
 'other',
 'output',
 'outside',
 'overhead',
 'overthink',
 'own',
 'packag',
 'packet',
 'packslip',
 'part',
 'passive',
 'passkey',
 'past',
 'pdf',
 'people',
 'per',
 'perform',
 'performance',
 'person',
 'personal',
 'perspective',
 'phon',
 'phone',
 'physic',
 'pioneer',
 'platform',
 'point',
 'polici',
 'political',
 'pooh',
 'portfolio',
 'post',
 'posture',
 'potential',
 'predict',
 'prevent',
 'privacy',
 'private',
 'prob',
 'probab',
 'process',
 'productivity',
 'profound',
 'project',
 'promo',
 'protect',
 'protection',
 'protein',
 'proxi',
 'punish',
 'push',
 'put',
 'q',
 'qbittorrent',
 'qq',
 'quantum',
 'question',
 'ratatui',
 'rather',
 'raw',
 're',
 'reactivate',
 'read',
 'ready',
 'real',
 'realiz',
 'reason',
 'rebuild',
 'rebuilt',
 'receiv',
 'recent',
 'reddit',
 'redditor',
 'reduc',
 'regular',
 'regulat',
 'reinstate',
 'reject',
 'relat',
 'release',
 'rely',
 'remover',
 'repeated',
 'report',
 'requir',
 'require',
 'respons',
 'restrict',
 'restriction',
 'reverse',
 'rewrite',
 'right',
 'role',
 'rough',
 'rul',
 'run',
 'runn',
 'rust',
 's',
 'safety',
 'said',
 'same',
 'sandbox',
 'say',
 'schemy',
 'scientist',
 'second',
 'security',
 'see',
 'selection',
 'self',
 'sensitive',
 'servic',
 'session',
 'share',
 'shell',
 'show',
 'shrink',
 'side',
 'sidecar',
 'sign',
 'similar',
 'simple',
 'single',
 'slop',
 'slow',
 'snoop',
 'some',
 'someone',
 'someth',
 'sometim',
 'sound',
 'source',
 'spac',
 'spam',
 'spe',
 'speak',
 'speculative',
 'speech',
 'spent',
 'ssh',
 'standard',
 'startup',
 'state',
 'statistic',
 'still',
 'story',
 'strange',
 'strict',
 'strong',
 'style',
 'substantial',
 'such',
 'support',
 'surpas',
 'surveillance',
 'syntax',
 'system',
 't',
 'taiwanese',
 'talk',
 'target',
 'tcp',
 'teach',
 'tech',
 'teenage',
 'tension',
 'terminal',
 'terrify',
 'test',
 'text',
 'thank',
 'therapeutic',
 'there',
 'thing',
 'think',
 'tied',
 'til',
 'tim',
 'time',
 'too',
 'took',
 'topic',
 'toward',
 'tracepoint',
 'train',
 'tre',
 'trend',
 'tri',
 'try',
 'tui',
 'two',
 'type',
 'udp',
 'underneath',
 'understand',
 'unifi',
 'unnecessary',
 'unreasonable',
 'until',
 'upcom',
 'use',
 'used',
 'user',
 'userspace',
 'using',
 'v',
 'variabl',
 've',
 'verification',
 'very',
 'via',
 'vib',
 'video',
 'violat',
 'vote',
 'vpn',
 'vs',
 'want',
 'wasn',
 'way',
 'web',
 'website',
 'wechat',
 'week',
 'weird',
 'what',
 'when',
 'whenever',
 'where',
 'who',
 'whole',
 'wikipedia',
 'window',
 'winnie',
 'within',
 'without',
 'wood',
 'word',
 'work',
 'world',
 'worri',
 'would',
 'wouldn',
 'wrapp',
 'written',
 'wrong',
 'xai',
 'xi',
 'year',
 'yes',
 'young',
 'zero']

## 10. Bag of Words

In [11]:
bow_df = bag_of_words(processed_docs, vocab)
bow_df

,able,acces,account,accurate,actual,add,addict,advertisement,affect,afraid,age,agent,ai,all,allow,...,word,work,world,worri,would,wouldn,wrapp,written,wrong,xai,xi,year,yes,young,zero
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
28,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0,0,0,0,0,2
29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,2,2,0,1,0,1,1,0,2,1,1,...,2,0,3,1,0,0,1,0,0,0,2,1,0,0,0
35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
37,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
43,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## 11. Binary Bag of Words

In [12]:
binary_df = binary_bow(processed_docs, vocab)
binary_df

,able,acces,account,accurate,actual,add,addict,advertisement,affect,afraid,age,agent,ai,all,allow,...,word,work,world,worri,would,wouldn,wrapp,written,wrong,xai,xi,year,yes,young,zero
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
28,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,1,1,0,1,0,1,1,0,1,1,1,...,1,0,1,1,0,0,1,0,0,0,1,1,0,0,0
35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
37,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
43,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## 12. One-Hot Encoding

Two flavors: one-hot per token *position* in a document (preserves order,
unlike bag-of-words), and a generic one-hot encoding of category labels
(here, the POS tags of Doc 0).

In [13]:
print("=== One-hot encoding of tokens (Doc 0) ===")
one_hot_tokens_df = one_hot_encode_tokens(processed_docs[0], vocab)
one_hot_tokens_df

=== One-hot encoding of tokens (Doc 0) ===

,able,acces,account,accurate,actual,add,addict,advertisement,affect,afraid,age,agent,ai,all,allow,...,word,work,world,worri,would,wouldn,wrapp,written,wrong,xai,xi,year,yes,young,zero
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [14]:
print("=== One-hot encoding of POS tags (Doc 0) ===")
pos_tags_doc0 = [tag for _, tag in pos_tag(raw_tokens_per_doc[0])]
one_hot_pos_df = one_hot_encode_categories(pos_tags_doc0)
one_hot_pos_df

=== One-hot encoding of POS tags (Doc 0) ===

   ADJ  DET  NOUN  PREP
0    0    1     0     0
1    1    0     0     0
2    1    0     0     0
3    0    0     0     1
4    0    0     1     0

## 13. TF-IDF

In [15]:
tfidf_df = tf_idf(processed_docs, vocab)
tfidf_df.round(3)

,able,acces,account,accurate,actual,add,addict,advertisement,affect,afraid,age,agent,ai,all,allow,...,word,work,world,worri,would,wouldn,wrapp,written,wrong,xai,xi,year,yes,young,zero
0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
5,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.912,0.000,0.000,0.000,0.000,0.000
6,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.219,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
7,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,23.472,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
8,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,3.912,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
9,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2.303,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
11,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
12,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
13,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2.813,0.000,0.000,0.000
14,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
15,3.912,3.912,11.736,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
16,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
17,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
18,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
19,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,2.526,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.912,0.000
20,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
21,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,2.526,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
23,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
24,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
26,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
27,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.912,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,3.912,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
28,0.000,0.000,0.000,3.912,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.912,0.000,0.000,0.000,0.000,0.000,0.000,7.824
29,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
30,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
31,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
32,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
33,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
34,0.000,0.000,0.000,0.000,7.824,7.824,0.000,3.912,0.000,3.912,3.912,0.000,4.605,3.912,3.912,...,7.824,0.000,7.577,3.912,0.000,0.000,3.912,0.000,0.000,0.000,7.824,2.813,0.000,0.000,0.000
35,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
36,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2.813,0.000,0.000,0.000
37,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.219,2.303,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
38,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
39,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
40,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2.303,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
41,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
42,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,2.526,0.000,0.000,0.000,0.000,0.000,3.912,0.000,0.000,0.000,0.000,0.000,0.000
43,0.000,0.000,0.000,0.000,0.000,0.000,3.912,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
44,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2.303,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
45,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
46,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
47,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.912,0.000,0.000
48,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
49,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

### Document Similarity (TF-IDF Cosine)

Pairwise cosine similarity between documents' TF-IDF vectors — lexical
overlap, not deep semantic meaning.

In [16]:
cosine_similarity_matrix(tfidf_df).round(3)

,doc_0,doc_1,doc_2,doc_3,doc_4,doc_5,doc_6,doc_7,doc_8,doc_9,doc_10,doc_11,doc_12,doc_13,doc_14,...,doc_35,doc_36,doc_37,doc_38,doc_39,doc_40,doc_41,doc_42,doc_43,doc_44,doc_45,doc_46,doc_47,doc_48,doc_49
doc_0,1.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_1,0.000,1.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_2,0.000,0.0,1.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.16,0.000,0.0
doc_3,0.000,0.0,0.00,1.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_4,0.000,0.0,0.00,0.0,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_5,0.000,0.0,0.00,0.0,0.000,1.000,0.000,0.012,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_6,0.000,0.0,0.00,0.0,0.000,0.000,1.000,0.021,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.268,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_7,0.000,0.0,0.00,0.0,0.000,0.012,0.021,1.000,0.011,0.012,0.000,0.0,0.009,0.000,0.000,...,0.017,0.000,0.000,0.0,0.000,0.000,0.0,0.021,0.010,0.000,0.0,0.000,0.00,0.034,0.0
doc_8,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.011,1.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_9,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.012,0.000,1.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.050,0.0,0.000,0.105,0.0,0.000,0.000,0.069,0.0,0.000,0.00,0.075,0.0
doc_10,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_11,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_12,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.009,0.000,0.000,0.000,0.0,1.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_13,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,1.000,0.000,...,0.000,0.234,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_14,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,1.000,...,0.000,0.000,0.000,0.0,0.000,0.517,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_15,0.000,0.0,0.00,0.0,0.000,0.048,0.000,0.050,0.021,0.010,0.076,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.062,0.000,0.0,0.000,0.00,0.014,0.0
doc_16,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_17,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.172,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_18,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.023,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_19,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.011,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.062,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_20,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.077,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_21,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.085,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_22,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.044,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_23,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_24,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_25,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.037,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_26,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_27,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.018,0.000,0.000,0.000,0.0,0.012,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.027,0.044,0.000,0.0,0.000,0.00,0.000,0.0
doc_28,0.000,0.0,0.00,0.0,0.000,0.033,0.022,0.029,0.018,0.023,0.033,0.0,0.000,0.000,0.000,...,0.017,0.000,0.000,0.0,0.000,0.000,0.0,0.052,0.000,0.000,0.0,0.000,0.00,0.055,0.0
doc_29,0.000,0.0,0.00,0.0,0.000,0.000,0.167,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.164,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_30,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_31,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.012,0.000,0.057,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.076,0.0
doc_32,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_33,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_34,0.013,0.0,0.00,0.0,0.008,0.009,0.008,0.081,0.018,0.009,0.009,0.0,0.005,0.007,0.000,...,0.000,0.008,0.010,0.0,0.022,0.022,0.0,0.131,0.054,0.014,0.0,0.017,0.00,0.003,0.0
doc_35,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.017,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,1.000,0.000,0.000,0.0,0.000,0.000,0.0,0.074,0.000,0.000,0.0,0.102,0.00,0.000,0.0
doc_36,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.234,0.000,...,0.000,1.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_37,0.000,0.0,0.00,0.0,0.000,0.000,0.268,0.000,0.000,0.050,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,1.000,0.0,0.000,0.161,0.0,0.000,0.000,0.106,0.0,0.000,0.00,0.000,0.0
doc_38,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,1.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_39,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,1.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_40,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.105,0.000,0.0,0.000,0.000,0.517,...,0.000,0.000,0.161,0.0,0.000,1.000,0.0,0.000,0.000,0.224,0.0,0.000,0.00,0.000,0.0
doc_41,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,1.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_42,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.021,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.074,0.000,0.000,0.0,0.000,0.000,0.0,1.000,0.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_43,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.010,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,1.000,0.000,0.0,0.000,0.00,0.000,0.0
doc_44,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.069,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.106,0.0,0.000,0.224,0.0,0.000,0.000,1.000,0.0,0.000,0.00,0.000,0.0
doc_45,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,1.0,0.000,0.00,0.000,0.0
doc_46,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.102,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,1.000,0.00,0.000,0.0
doc_47,0.000,0.0,0.16,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,1.00,0.000,0.0
doc_48,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.034,0.000,0.075,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,1.000,0.0
doc_49,0.000,0.0,0.00,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.00,0.000,1.0

## 14. N-grams

Bigrams and trigrams for every document, built from the fully preprocessed
tokens.

In [17]:
for i, tokens in enumerate(processed_docs):
    print(f"Doc {i}")
    print("  Bigrams: ", n_grams(tokens, 2))
    print("  Trigrams:", n_grams(tokens, 3))

Doc 0
  Bigrams:  [('therapeutic', 'potential'), ('potential', 'apigenin')]
  Trigrams: [('therapeutic', 'potential', 'apigenin')]
Doc 1
  Bigrams:  [('interactive', 'physic')]
  Trigrams: []
Doc 2
  Bigrams:  [('economic', 'intelligence'), ('intelligence', 'frontier')]
  Trigrams: [('economic', 'intelligence', 'frontier')]
Doc 3
  Bigrams:  [('packslip', 'sign'), ('sign', 'release'), ('release', 'manifest'), ('manifest', 'archiv'), ('archiv', 'installer'), ('installer', 'executabl')]
  Trigrams: [('packslip', 'sign', 'release'), ('sign', 'release', 'manifest'), ('release', 'manifest', 'archiv'), ('manifest', 'archiv', 'installer'), ('archiv', 'installer', 'executabl')]
Doc 4
  Bigrams:  [('innovative', 'hp'), ('hp', 'computer'), ('computer', 'behind'), ('behind', 'hedge'), ('hedge', 'fund'), ('fund', 'pioneer')]
  Trigrams: [('innovative', 'hp', 'computer'), ('hp', 'computer', 'behind'), ('computer', 'behind', 'hedge'), ('behind', 'hedge', 'fund'), ('hedge', 'fund', 'pioneer')]
Doc 5
  Bigrams:  [('federal', 'judge'), ('judge', 'rul'), ('rul', 'musk'), ('musk', 's'), ('s', 'xai')]
  Trigrams: [('federal', 'judge', 'rul'), ('judge', 'rul', 'musk'), ('rul', 'musk', 's'), ('musk', 's', 'xai')]
Doc 6
  Bigrams:  [('til', 'using'), ('using', 'blender'), ('blender', 'cod'), ('cod', 'agent'), ('agent', 'maco')]
  Trigrams: [('til', 'using', 'blender'), ('using', 'blender', 'cod'), ('blender', 'cod', 'agent'), ('cod', 'agent', 'maco')]
Doc 7
  Bigrams:  [('show', 'hn'), ('hn', 'markflowy'), ('markflowy', 'open'), ('open', 'source'), ('source', 'markdown'), ('markdown', 'editor'), ('editor', 'rebuilt'), ('rebuilt', 'large'), ('large', 'document'), ('document', 'maintain'), ('maintain', 'markflowy'), ('markflowy', 'desktop'), ('desktop', 'markdown'), ('markdown', 'editor'), ('editor', 'window'), ('window', 'maco'), ('maco', 'linux'), ('linux', 've'), ('ve', 'spent'), ('spent', 'past'), ('past', 'two'), ('two', 'month'), ('month', 'rebuild'), ('rebuild', 'editor'), ('editor', 'core'), ('core', 'main'), ('main', 'improve'), ('improve', 'performance'), ('performance', 'larger'), ('larger', 'document'), ('document', 'chang'), ('chang', 'part'), ('part', 'v'), ('v', 'test'), ('test', 'mb'), ('mb', 'markdown'), ('markdown', 'document'), ('document', 'open'), ('open', 'second'), ('second', 'd'), ('d', 'interest'), ('interest', 'see'), ('see', 'how'), ('how', 'perform'), ('perform', 'other'), ('other', 'people'), ('people', 's'), ('s', 'document'), ('document', 'hardware'), ('hardware', 'open'), ('open', 'spe'), ('spe', 'one'), ('one', 'part'), ('part', 'work'), ('work', 'also'), ('also', 'work'), ('work', 'edit'), ('edit', 'long'), ('long', 'document'), ('document', 'copy'), ('copy', 'cutt'), ('cutt', 'large'), ('large', 'selection'), ('selection', 'much'), ('much', 'overhead'), ('overhead', 'came'), ('came', 'repeated'), ('repeated', 'process'), ('process', 'entire'), ('entire', 'document'), ('document', 'unnecessary'), ('unnecessary', 'work'), ('work', 'within'), ('within', 'single'), ('single', 'operation'), ('operation', 'find'), ('find', 'reduc'), ('reduc', 'work'), ('work', 'took'), ('took', 'substantial'), ('substantial', 'part'), ('part', 'rewrite'), ('rewrite', 'want'), ('want', 'thank'), ('thank', 'user'), ('user', 'who'), ('who', 'report'), ('report', 'bug'), ('bug', 'slow'), ('slow', 'operation'), ('operation', 'awkward'), ('awkward', 'interaction'), ('interaction', 'report'), ('report', 'help'), ('help', 'understand'), ('understand', 'where'), ('where', 'focu'), ('focu', 'rewrite'), ('rewrite', 'chang'), ('chang', 'some'), ('some', 'edit'), ('edit', 'behavior'), ('behavior', 'there'), ('there', 'still'), ('still', 'rough'), ('rough', 'edg'), ('edg', 'work'), ('work', 'regular'), ('regular', 'work'), ('work', 'long'), ('long', 'markdown'), ('markdown', 'document'), ('document', 'd'), ('d', 'appreciate'), ('appreciate', 'feedback'), ('feedback', 'anyth'), ('anyth', 'still'), ('still', 'feel'), ('feel', 'slow'), ('slow', 'get'), ('get', 'way'), ('way', 'project'), ('project', 'download'), ('download', 'http'), ('http', 'github'), ('github', 'com'), ('com', 'drl'), ('drl', 'markflowy')]
  Trigrams: [('show', 'hn', 'markflowy'), ('hn', 'markflowy', 'open'), ('markflowy', 'open', 'source'), ('open', 'source', 'markdown'), ('source', 'markdown', 'editor'), ('markdown', 'editor', 'rebuilt'), ('editor', 'rebuilt', 'large'), ('rebuilt', 'large', 'document'), ('large', 'document', 'maintain'), ('document', 'maintain', 'markflowy'), ('maintain', 'markflowy', 'desktop'), ('markflowy', 'desktop', 'markdown'), ('desktop', 'markdown', 'editor'), ('markdown', 'editor', 'window'), ('editor', 'window', 'maco'), ('window', 'maco', 'linux'), ('maco', 'linux', 've'), ('linux', 've', 'spent'), ('ve', 'spent', 'past'), ('spent', 'past', 'two'), ('past', 'two', 'month'), ('two', 'month', 'rebuild'), ('month', 'rebuild', 'editor'), ('rebuild', 'editor', 'core'), ('editor', 'core', 'main'), ('core', 'main', 'improve'), ('main', 'improve', 'performance'), ('improve', 'performance', 'larger'), ('performance', 'larger', 'document'), ('larger', 'document', 'chang'), ('document', 'chang', 'part'), ('chang', 'part', 'v'), ('part', 'v', 'test'), ('v', 'test', 'mb'), ('test', 'mb', 'markdown'), ('mb', 'markdown', 'document'), ('markdown', 'document', 'open'), ('document', 'open', 'second'), ('open', 'second', 'd'), ('second', 'd', 'interest'), ('d', 'interest', 'see'), ('interest', 'see', 'how'), ('see', 'how', 'perform'), ('how', 'perform', 'other'), ('perform', 'other', 'people'), ('other', 'people', 's'), ('people', 's', 'document'), ('s', 'document', 'hardware'), ('document', 'hardware', 'open'), ('hardware', 'open', 'spe'), ('open', 'spe', 'one'), ('spe', 'one', 'part'), ('one', 'part', 'work'), ('part', 'work', 'also'), ('work', 'also', 'work'), ('also', 'work', 'edit'), ('work', 'edit', 'long'), ('edit', 'long', 'document'), ('long', 'document', 'copy'), ('document', 'copy', 'cutt'), ('copy', 'cutt', 'large'), ('cutt', 'large', 'selection'), ('large', 'selection', 'much'), ('selection', 'much', 'overhead'), ('much', 'overhead', 'came'), ('overhead', 'came', 'repeated'), ('came', 'repeated', 'process'), ('repeated', 'process', 'entire'), ('process', 'entire', 'document'), ('entire', 'document', 'unnecessary'), ('document', 'unnecessary', 'work'), ('unnecessary', 'work', 'within'), ('work', 'within', 'single'), ('within', 'single', 'operation'), ('single', 'operation', 'find'), ('operation', 'find', 'reduc'), ('find', 'reduc', 'work'), ('reduc', 'work', 'took'), ('work', 'took', 'substantial'), ('took', 'substantial', 'part'), ('substantial', 'part', 'rewrite'), ('part', 'rewrite', 'want'), ('rewrite', 'want', 'thank'), ('want', 'thank', 'user'), ('thank', 'user', 'who'), ('user', 'who', 'report'), ('who', 'report', 'bug'), ('report', 'bug', 'slow'), ('bug', 'slow', 'operation'), ('slow', 'operation', 'awkward'), ('operation', 'awkward', 'interaction'), ('awkward', 'interaction', 'report'), ('interaction', 'report', 'help'), ('report', 'help', 'understand'), ('help', 'understand', 'where'), ('understand', 'where', 'focu'), ('where', 'focu', 'rewrite'), ('focu', 'rewrite', 'chang'), ('rewrite', 'chang', 'some'), ('chang', 'some', 'edit'), ('some', 'edit', 'behavior'), ('edit', 'behavior', 'there'), ('behavior', 'there', 'still'), ('there', 'still', 'rough'), ('still', 'rough', 'edg'), ('rough', 'edg', 'work'), ('edg', 'work', 'regular'), ('work', 'regular', 'work'), ('regular', 'work', 'long'), ('work', 'long', 'markdown'), ('long', 'markdown', 'document'), ('markdown', 'document', 'd'), ('document', 'd', 'appreciate'), ('d', 'appreciate', 'feedback'), ('appreciate', 'feedback', 'anyth'), ('feedback', 'anyth', 'still'), ('anyth', 'still', 'feel'), ('still', 'feel', 'slow'), ('feel', 'slow', 'get'), ('slow', 'get', 'way'), ('get', 'way', 'project'), ('way', 'project', 'download'), ('project', 'download', 'http'), ('download', 'http', 'github'), ('http', 'github', 'com'), ('github', 'com', 'drl'), ('com', 'drl', 'markflowy')]
Doc 8
  Bigrams:  [('how', 'would'), ('would', 'llm'), ('llm', 'vote'), ('vote', 'upcom'), ('upcom', 'german'), ('german', 'state'), ('state', 'election')]
  Trigrams: [('how', 'would', 'llm'), ('would', 'llm', 'vote'), ('llm', 'vote', 'upcom'), ('vote', 'upcom', 'german'), ('upcom', 'german', 'state'), ('german', 'state', 'election')]
Doc 9
  Bigrams:  [('show', 'hn'), ('hn', 'object'), ('object', 'remover'), ('remover', 'ai'), ('ai', 'video'), ('video', 'object'), ('object', 'remover'), ('remover', 'online')]
  Trigrams: [('show', 'hn', 'object'), ('hn', 'object', 'remover'), ('object', 'remover', 'ai'), ('remover', 'ai', 'video'), ('ai', 'video', 'object'), ('video', 'object', 'remover'), ('object', 'remover', 'online')]
Doc 10
  Bigrams:  [('could', 'come'), ('come', 'speculative'), ('speculative', 'decod')]
  Trigrams: [('could', 'come', 'speculative'), ('come', 'speculative', 'decod')]
Doc 11
  Bigrams:  [('gompertz', 'makeham'), ('makeham', 'law'), ('law', 'mortality')]
  Trigrams: [('gompertz', 'makeham', 'law'), ('makeham', 'law', 'mortality')]
Doc 12
  Bigrams:  [('lost', 'byt'), ('byt', 'crossroad'), ('crossroad', 'user'), ('user', 'kernel'), ('kernel', 'level'), ('level', 'memory'), ('memory', 'management'), ('management', 'pdf')]
  Trigrams: [('lost', 'byt', 'crossroad'), ('byt', 'crossroad', 'user'), ('crossroad', 'user', 'kernel'), ('user', 'kernel', 'level'), ('kernel', 'level', 'memory'), ('level', 'memory', 'management'), ('memory', 'management', 'pdf')]
Doc 13
  Bigrams:  [('year', 'old'), ('old', 'japanese'), ('japanese', 'book'), ('book', 'predict'), ('predict', 'productivity'), ('productivity', 'crisi')]
  Trigrams: [('year', 'old', 'japanese'), ('old', 'japanese', 'book'), ('japanese', 'book', 'predict'), ('book', 'predict', 'productivity'), ('predict', 'productivity', 'crisi')]
Doc 14
  Bigrams:  [('infinite', 'slop')]
  Trigrams: []
Doc 15
  Bigrams:  [('ask', 'hn'), ('hn', 'how'), ('how', 'reactivate'), ('reactivate', 'chatgpt'), ('chatgpt', 'account'), ('account', 'receiv'), ('receiv', 'notice'), ('notice', 'account'), ('account', 'deactivat'), ('deactivat', 'wasn'), ('wasn', 't'), ('t', 'anyth'), ('anyth', 'weird'), ('weird', 'inappropriate'), ('inappropriate', 'don'), ('don', 't'), ('t', 'acces'), ('acces', 'chat'), ('chat', 'anymore'), ('anymore', 'able'), ('able', 'see'), ('see', 'some'), ('some', 'recent'), ('recent', 'chat'), ('chat', 'could'), ('could', 'annotate'), ('annotate', 'here'), ('here', 'there'), ('there', 's'), ('s', 'noth'), ('noth', 'weird'), ('weird', 'http'), ('http', 'imgur'), ('imgur', 'com'), ('com', 'q'), ('q', 'heo'), ('heo', 'e'), ('e', 'there'), ('there', 'any'), ('any', 'way'), ('way', 'could'), ('could', 'escalate'), ('escalate', 'someone'), ('someone', 'openai'), ('openai', 'reinstate'), ('reinstate', 'account'), ('account', 'fil'), ('fil', 'appeal'), ('appeal', 'don'), ('don', 't'), ('t', 'know'), ('know', 's'), ('s', 'enough')]
  Trigrams: [('ask', 'hn', 'how'), ('hn', 'how', 'reactivate'), ('how', 'reactivate', 'chatgpt'), ('reactivate', 'chatgpt', 'account'), ('chatgpt', 'account', 'receiv'), ('account', 'receiv', 'notice'), ('receiv', 'notice', 'account'), ('notice', 'account', 'deactivat'), ('account', 'deactivat', 'wasn'), ('deactivat', 'wasn', 't'), ('wasn', 't', 'anyth'), ('t', 'anyth', 'weird'), ('anyth', 'weird', 'inappropriate'), ('weird', 'inappropriate', 'don'), ('inappropriate', 'don', 't'), ('don', 't', 'acces'), ('t', 'acces', 'chat'), ('acces', 'chat', 'anymore'), ('chat', 'anymore', 'able'), ('anymore', 'able', 'see'), ('able', 'see', 'some'), ('see', 'some', 'recent'), ('some', 'recent', 'chat'), ('recent', 'chat', 'could'), ('chat', 'could', 'annotate'), ('could', 'annotate', 'here'), ('annotate', 'here', 'there'), ('here', 'there', 's'), ('there', 's', 'noth'), ('s', 'noth', 'weird'), ('noth', 'weird', 'http'), ('weird', 'http', 'imgur'), ('http', 'imgur', 'com'), ('imgur', 'com', 'q'), ('com', 'q', 'heo'), ('q', 'heo', 'e'), ('heo', 'e', 'there'), ('e', 'there', 'any'), ('there', 'any', 'way'), ('any', 'way', 'could'), ('way', 'could', 'escalate'), ('could', 'escalate', 'someone'), ('escalate', 'someone', 'openai'), ('someone', 'openai', 'reinstate'), ('openai', 'reinstate', 'account'), ('reinstate', 'account', 'fil'), ('account', 'fil', 'appeal'), ('fil', 'appeal', 'don'), ('appeal', 'don', 't'), ('don', 't', 'know'), ('t', 'know', 's'), ('know', 's', 'enough')]
Doc 16
  Bigrams:  [('mortgage', 'calculator')]
  Trigrams: []
Doc 17
  Bigrams:  [('llm', 'new'), ('new', 'wikipedia')]
  Trigrams: [('llm', 'new', 'wikipedia')]
Doc 18
  Bigrams:  [('claude', 'compiler'), ('compiler', 'dead'), ('dead', 'long'), ('long', 'live'), ('live', 'claude'), ('claude', 'compiler')]
  Trigrams: [('claude', 'compiler', 'dead'), ('compiler', 'dead', 'long'), ('dead', 'long', 'live'), ('long', 'live', 'claude'), ('live', 'claude', 'compiler')]
Doc 19
  Bigrams:  [('older', 'people'), ('people', 'surpas'), ('surpas', 'young'), ('young', 'world'), ('world', 'first'), ('first', 'time'), ('time', 'history')]
  Trigrams: [('older', 'people', 'surpas'), ('people', 'surpas', 'young'), ('surpas', 'young', 'world'), ('young', 'world', 'first'), ('world', 'first', 'time'), ('first', 'time', 'history')]
Doc 20
  Bigrams:  [('modern', 'day'), ('day', 'american'), ('american', 'imperialism'), ('imperialism', 'middle'), ('middle', 'east'), ('east', 'beyond'), ('beyond', 'video')]
  Trigrams: [('modern', 'day', 'american'), ('day', 'american', 'imperialism'), ('american', 'imperialism', 'middle'), ('imperialism', 'middle', 'east'), ('middle', 'east', 'beyond'), ('east', 'beyond', 'video')]
Doc 21
  Bigrams:  [('icy', 'moon'), ('moon', 'ocean'), ('ocean', 'world')]
  Trigrams: [('icy', 'moon', 'ocean'), ('moon', 'ocean', 'world')]
Doc 22
  Bigrams:  [('currency', 'killer'), ('killer', 'part'), ('part', 'ii'), ('ii', 'howard'), ('howard', 'lutnick')]
  Trigrams: [('currency', 'killer', 'part'), ('killer', 'part', 'ii'), ('part', 'ii', 'howard'), ('ii', 'howard', 'lutnick')]
Doc 23
  Bigrams:  [('tre', 'use'), ('use', 'muscle'), ('muscle', 'correct'), ('correct', 'posture'), ('posture', 'new'), ('new', 'discover'), ('discover', 'role'), ('role', 'tension'), ('tension', 'wood')]
  Trigrams: [('tre', 'use', 'muscle'), ('use', 'muscle', 'correct'), ('muscle', 'correct', 'posture'), ('correct', 'posture', 'new'), ('posture', 'new', 'discover'), ('new', 'discover', 'role'), ('discover', 'role', 'tension'), ('role', 'tension', 'wood')]
Doc 24
  Bigrams:  [('support', 'local'), ('local', 'variabl')]
  Trigrams: [('support', 'local', 'variabl')]
Doc 25
  Bigrams:  [('tim', 'berner'), ('berner', 'lee'), ('lee', 'call'), ('call', 'continu'), ('continu', 'open'), ('open', 'standard'), ('standard', 'neutrality')]
  Trigrams: [('tim', 'berner', 'lee'), ('berner', 'lee', 'call'), ('lee', 'call', 'continu'), ('call', 'continu', 'open'), ('continu', 'open', 'standard'), ('open', 'standard', 'neutrality')]
Doc 26
  Bigrams:  [('qbittorrent', 'break'), ('break', 'sandbox'), ('sandbox', 'commit'), ('commit', 'crim')]
  Trigrams: [('qbittorrent', 'break', 'sandbox'), ('break', 'sandbox', 'commit'), ('sandbox', 'commit', 'crim')]
Doc 27
  Bigrams:  [('reddit', 'anti'), ('anti', 'self'), ('self', 'promo'), ('promo', 'polici'), ('polici', 'destroy'), ('destroy', 'startup'), ('startup', 'm'), ('m', 'post'), ('post', 'here'), ('here', 'because'), ('because', 'reddit'), ('reddit', 'just'), ('just', 'ban'), ('ban', 'whenever'), ('whenever', 'talk'), ('talk', 'let'), ('let', 'explain'), ('explain', 'reddit'), ('reddit', 'anti'), ('anti', 'self'), ('self', 'promo'), ('promo', 'polici'), ('polici', 'prevent'), ('prevent', 'spam'), ('spam', 'enforc'), ('enforc', 'strict'), ('strict', 'reddit'), ('reddit', 'mod'), ('mod', 'even'), ('even', 'user'), ('user', 'becom'), ('becom', 'near'), ('near', 'impossible'), ('impossible', 'share'), ('share', 'startup'), ('startup', 'now'), ('now', 'reddit'), ('reddit', 'itself'), ('itself', 'wouldn'), ('wouldn', 't'), ('t', 'get'), ('get', 'startup'), ('startup', 'big'), ('big', 'prevent'), ('prevent', 'even'), ('even', 'reject'), ('reject', 'caus'), ('caus', 'people'), ('people', 'who'), ('who', 'make'), ('make', 'bad'), ('bad', 'startup'), ('startup', 'even'), ('even', 'know'), ('know', 'thing'), ('thing', 'bad'), ('bad', 'lead'), ('lead', 'long'), ('long', 'drawn'), ('drawn', 'failur'), ('failur', 'even'), ('even', 'affect'), ('affect', 'thing'), ('thing', 'outside'), ('outside', 'reddit'), ('reddit', 'shrink'), ('shrink', 'available'), ('available', 'spac'), ('spac', 'can'), ('can', 'share'), ('share', 'startup'), ('startup', 'much'), ('much', 'redditor'), ('redditor', 'common'), ('common', 'man')]
  Trigrams: [('reddit', 'anti', 'self'), ('anti', 'self', 'promo'), ('self', 'promo', 'polici'), ('promo', 'polici', 'destroy'), ('polici', 'destroy', 'startup'), ('destroy', 'startup', 'm'), ('startup', 'm', 'post'), ('m', 'post', 'here'), ('post', 'here', 'because'), ('here', 'because', 'reddit'), ('because', 'reddit', 'just'), ('reddit', 'just', 'ban'), ('just', 'ban', 'whenever'), ('ban', 'whenever', 'talk'), ('whenever', 'talk', 'let'), ('talk', 'let', 'explain'), ('let', 'explain', 'reddit'), ('explain', 'reddit', 'anti'), ('reddit', 'anti', 'self'), ('anti', 'self', 'promo'), ('self', 'promo', 'polici'), ('promo', 'polici', 'prevent'), ('polici', 'prevent', 'spam'), ('prevent', 'spam', 'enforc'), ('spam', 'enforc', 'strict'), ('enforc', 'strict', 'reddit'), ('strict', 'reddit', 'mod'), ('reddit', 'mod', 'even'), ('mod', 'even', 'user'), ('even', 'user', 'becom'), ('user', 'becom', 'near'), ('becom', 'near', 'impossible'), ('near', 'impossible', 'share'), ('impossible', 'share', 'startup'), ('share', 'startup', 'now'), ('startup', 'now', 'reddit'), ('now', 'reddit', 'itself'), ('reddit', 'itself', 'wouldn'), ('itself', 'wouldn', 't'), ('wouldn', 't', 'get'), ('t', 'get', 'startup'), ('get', 'startup', 'big'), ('startup', 'big', 'prevent'), ('big', 'prevent', 'even'), ('prevent', 'even', 'reject'), ('even', 'reject', 'caus'), ('reject', 'caus', 'people'), ('caus', 'people', 'who'), ('people', 'who', 'make'), ('who', 'make', 'bad'), ('make', 'bad', 'startup'), ('bad', 'startup', 'even'), ('startup', 'even', 'know'), ('even', 'know', 'thing'), ('know', 'thing', 'bad'), ('thing', 'bad', 'lead'), ('bad', 'lead', 'long'), ('lead', 'long', 'drawn'), ('long', 'drawn', 'failur'), ('drawn', 'failur', 'even'), ('failur', 'even', 'affect'), ('even', 'affect', 'thing'), ('affect', 'thing', 'outside'), ('thing', 'outside', 'reddit'), ('outside', 'reddit', 'shrink'), ('reddit', 'shrink', 'available'), ('shrink', 'available', 'spac'), ('available', 'spac', 'can'), ('spac', 'can', 'share'), ('can', 'share', 'startup'), ('share', 'startup', 'much'), ('startup', 'much', 'redditor'), ('much', 'redditor', 'common'), ('redditor', 'common', 'man')]
Doc 28

## Summary

```
raw text -> lowercase -> remove punctuation/numbers -> tokenize
         -> remove stopwords -> stem/lemmatize
         -> [POS tagging / syntactic / semantic / morphological on the side]
         -> feature extraction (BoW / one-hot / TF-IDF / cosine similarity / n-grams)
```

Every step above is implemented from scratch in `preprocessing.py`,
`linguistic_features.py`, `syntactic_features.py`, `semantic_features.py`,
and `features.py` using only `numpy` and `pandas`. See `report.md` for the
theory behind each step.